# Generated by Django 4.1.5 on 2023-01-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="guess_can_pause",
            new_name="guest_can_pause",
        ),
    ]
